<?php

use flowcode\demo\domain\Weapon;
use flowcode\ceibo\builder\MapperBuilder;
use flowcode\ceibo\domain\Collection;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-31 at 02:42:14.
 */
class CollectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Collection
     */
    protected $object;
    private $raw = array();

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->raw = array(
            array("id" => 1, "name" => "lazer"),
        );

        $class = "\\flowcode\\demo\\domain\\Weapon";

        $mappingFilePath = dirname(__FILE__) . "/../ceibo-mapping-test.xml";
        $mapping = simplexml_load_file($mappingFilePath);

        $mapper = MapperBuilder::buildFromName($mapping, "weapon");
        $this->object = new Collection($class, $this->raw, $mapper);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Collection::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        $weapon1 = new Weapon(2, "zord");
        $this->object->add($weapon1);

        $weaponInCollection = $this->object->current();
        $this->assertEquals(1, $weaponInCollection->getId());
        $this->assertEquals("lazer", $weaponInCollection->getName());
        $this->assertEquals(2, $this->object->count());
    }

    /**
     * @covers Collection::getTargetClass
     * @todo   Implement testGetTargetClass().
     */
    public function testGetTargetClass() {
        $this->assertEquals("\\flowcode\\demo\\domain\\Weapon", $this->object->getTargetClass());
    }

    /**
     * @covers Collection::rewind
     * @todo   Implement testRewind().
     */
    public function testRewind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Collection::current
     * @todo   Implement testCurrent().
     */
    public function testCurrent() {
        $weapon1 = new Weapon(2, "zord");
        $this->object->add($weapon1);
        $weapon2 = new Weapon(3, "lazer 2");
        $this->object->add($weapon2);

        $this->object->next();
        $this->assertEquals(2, $this->object->current()->getId());
        
        $this->object->next();
        $this->assertEquals(3, $this->object->current()->getId());

    }

    /**
     * @covers Collection::key
     * @todo   Implement testKey().
     */
    public function testKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Collection::next
     * @todo   Implement testNext().
     */
    public function testNext() {
        $weaponInCollection = $this->object->next();
        $this->assertEquals(1, $weaponInCollection->getId());
        $this->assertEquals("lazer", $weaponInCollection->getName());
    }

    /**
     * @covers Collection::valid
     * @todo   Implement testValid().
     */
    public function testValid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
