<?php

namespace flowcode\ceibo;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-22 at 21:42:01.
 * @group need-db
 */
class EntityManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EntityManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = EntityManager::getInstance();
        $this->object->setMappingFilePath(dirname(__FILE__) . "/orm-mapping-test.xml");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\ceibo\EntityManager::save
     * @todo   Implement testSave().
     */
    public function testSave_ovniWithoutWeapons_success() {
        $ovni = new Ovni();
        $ovni->setName("ovni1");

        /* datasource mock */
        $dataSource = $this->getMock('flowcode\ceibo\data\PDOMySqlDataSource', array('executeNonQuery', 'executeQuery', 'executeInsert', 'escapeString'));
        $dataSource->expects($this->any())
                ->method('escapeString')
                ->will($this->returnArgument(0));
        $dataSource->expects($this->once())
                ->method('executeInsert')
                ->with($this->equalTo("INSERT INTO `ovni` (`name`) VALUES ('ovni1');"));

        $this->object->setDataSource($dataSource);

        $this->object->save($ovni);
    }

    /**
     * @covers flowcode\ceibo\EntityManager::findAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::findById
     * @todo   Implement testFindById().
     */
    public function testFindById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::findRelation
     * @todo   Implement testFindRelation().
     */
    public function testFindRelation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::findByWhereFilter
     * @todo   Implement testFindByWhereFilter().
     */
    public function testFindByWhereFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::findByGenericFilter
     * @todo   Implement testFindByGenericFilter().
     */
    public function testFindByGenericFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::getDataSource
     * @todo   Implement testGetDataSource().
     */
    public function testGetDataSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::setDataSource
     * @todo   Implement testSetDataSource().
     */
    public function testSetDataSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::getMappingFilePath
     * @todo   Implement testGetMappingFilePath().
     */
    public function testGetMappingFilePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::setMappingFilePath
     * @todo   Implement testSetMappingFilePath().
     */
    public function testSetMappingFilePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::getMapping
     * @todo   Implement testGetMapping().
     */
    public function testGetMapping() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\ceibo\EntityManager::setMapping
     * @todo   Implement testSetMapping().
     */
    public function testSetMapping() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
class Ovni {

    private $id;
    private $name;
    private $weapons = array();

    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
    }

    public function getName() {
        return $this->name;
    }

    public function setName($name) {
        $this->name = $name;
    }
    
    public function getWeapons() {
        return $this->weapons;
    }

    public function setWeapons($weapons) {
        $this->weapons = $weapons;
    }



}

class Weapon {

    private $id;
    private $name;

    function __construct() {
        
    }

    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
    }

    public function getName() {
        return $this->name;
    }

    public function setName($name) {
        $this->name = $name;
    }

}