<?php

use flowcode\demo\domain\Weapon;
use flowcode\orm\builder\MapperBuilder;
use flowcode\orm\domain\Collection;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-31 at 02:42:14.
 */
class CollectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Collection
     */
    protected $object;
    private $raw = array();

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->raw[] = array("id" => 1, "name" => "lazer");

        $class = "\\flowcode\\demo\\domain\\Weapon";

        $mappingFilePath = dirname(__FILE__) . "/../orm-mapping-test.xml";
        $mapping = simplexml_load_file($mappingFilePath);

        $mapper = MapperBuilder::buildFromMapping($mapping, $class);

        $this->object = new Collection($class, $this->raw, $mapper);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Collection::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        $weapon1 = new Weapon(2, "lazer");
        $this->object->add($weapon1);
        //$this->assertEquals(2, $this->object->count());
        //$this->assertEquals(0, $this->object->key());
        //$this->assertTrue($this->object->valid());
        
        $w = $this->object->current();
        print_r($w);
        $this->assertEquals("lazer", $w->getName());
    }

    /**
     * @covers Collection::getTargetClass
     * @todo   Implement testGetTargetClass().
     */
    public function testGetTargetClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Collection::setTargetClass
     * @todo   Implement testSetTargetClass().
     */
    public function testSetTargetClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Collection::rewind
     * @todo   Implement testRewind().
     */
    public function testRewind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Collection::current
     * @todo   Implement testCurrent().
     */
    public function testCurrent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Collection::key
     * @todo   Implement testKey().
     */
    public function testKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Collection::next
     * @todo   Implement testNext().
     */
    public function testNext() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Collection::valid
     * @todo   Implement testValid().
     */
    public function testValid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
